language: php
sudo: required
php:
- 5.5
- 5.6
#- 7.0
#- 7.1
#- nightly
#- hhvm-3.3
#- hhvm-3.6

#matrix:
#  allow_failures:
#    - php: hhvm-3.3
#    - php: hhvm-3.6
#    - php: nightly

addons:
  apt:
    packages:
      - gearman-job-server
      - libgearman-dev

before_install:
  - pecl install gearman-1.0.3
  - composer self-update
  - composer global require "fxp/composer-asset-plugin:*"
  - composer install

install:
  - composer run build-tests

before_script:
  - gearmand -d

script:
  - composer run tests

after_success:
  - cat tests/_output/log.txt